2023-12-18 23:53:39,837 ERROR: Exception on /api/map [GET] [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/api/routes.py", line 30, in map
    for r in result:
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2900, in __iter__
    result = self._iter()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2915, in _iter
    result = self.session.execute(
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 611, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'inactive' state, due to the SQL transaction being rolled back; no further SQL can be emitted within this transaction.
2023-12-18 23:54:25,355 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2023-12-18 23:54:25,900 ERROR: Exception on /api/map [GET] [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/api/routes.py", line 30, in map
    for r in result:
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2900, in __iter__
    result = self._iter()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2915, in _iter
    result = self.session.execute(
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 611, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'inactive' state, due to the SQL transaction being rolled back; no further SQL can be emitted within this transaction.
2023-12-18 23:56:08,292 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2023-12-18 23:56:20,851 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2023-12-18 23:56:44,091 ERROR: Exception on /api/map [GET] [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/api/routes.py", line 30, in map
    for r in result:
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2900, in __iter__
    result = self._iter()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2915, in _iter
    result = self.session.execute(
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 611, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'inactive' state, due to the SQL transaction being rolled back; no further SQL can be emitted within this transaction.
2023-12-19 01:11:03,951 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2023-12-19 01:14:40,484 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2023-12-19 01:15:56,527 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2023-12-19 01:16:17,097 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2023-12-19 01:18:09,036 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2024-01-08 15:09:15,884 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
2025-02-21 20:59:07,757 INFO: Project startup [in /mnt/c/Users/willw/Documents/GitHub/projet_photo/microblog/app/__init__.py:98]
